lmax_over_nside = 2.5
healpix = true
car = false
output_folder = "output_lsq/{nside}/{tag}/0000"
output_filename_template= "cmbs4_{tag}_uKCMB_{telescope}-{band}_nside{nside}_0000.fits"
unit = "uK_CMB"
num = 0
output_reference_frame = "C"
instrument_parameters = "instrument_model/cmbs4_instrument_model.tbl"
