lmax_over_nside = 2.5
nside = 2048
healpix = true
car = false
output_folder = "output/{tag}"
output_filename_template= "spt_{tag}_uKCMB_{telescope}-{band}_nside{nside}.fits"
unit = "uK_CMB"
num = 0
output_reference_frame = "C"
instrument_parameters = "../private/202308_panexp_spt3g/spt_instrument_model.tbl"
