output_folder = "output/{nside}/{tag}/0000"
output_filename_template= "cmbs4_{tag}_uKCMB_{telescope}-{band}_nside{nside}_0000.fits"
unit = "uK_CMB"
num = 0
mapsims_version = "2.2.0"
so_pysm_models_version = "2.2.0"
instrument_parameters = "cmbs4_tophat.h5"
